#!/bin/bash

echo "🚀 Smart Vitals Deployment Script"
echo "=================================="

echo ""
echo "📋 Pre-deployment Checklist:"
echo "1. ✅ Backend files prepared (railway.json, Procfile)"
echo "2. ✅ Frontend files prepared (vercel.json)"
echo "3. ✅ Environment variables ready"
echo "4. ✅ GitHub repository connected"

echo ""
echo "🔧 Backend Deployment (Railway):"
echo "1. Go to https://railway.app"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose Smart_Vitals repository"
echo "6. Set root directory to: Smart_Vitals/Backend"
echo "7. Configure environment variables"
echo "8. Deploy"

echo ""
echo "🌐 Frontend Deployment (Vercel):"
echo "1. Go to https://vercel.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New Project'"
echo "4. Import Smart_Vitals repository"
echo "5. Set root directory to: Smart_Vitals/FrontEnd"
echo "6. Framework preset: Vite"
echo "7. Configure environment variables"
echo "8. Deploy"

echo ""
echo "🔄 Post-deployment Steps:"
echo "1. Update CORS in Railway backend with frontend URL"
echo "2. Test API endpoints"
echo "3. Test frontend-backend communication"
echo "4. Update domain names if needed"

echo ""
echo "📚 For detailed instructions, see: DEPLOYMENT_GUIDE.md"
echo ""
echo "Happy Deploying! 🚀"
